### ISSUE TITLE
Filter by resource

### ISSUE THREAD

**Issue by ghost** [TerhoAntila/planner-gantt-chart#1]
This is a great app by the way, disappointing that you have to create it to resolve a lack of core feature! 

Another issue I have with planner is the lack of ability to see tasks across multiple plans for a single user, and this app looks like it could also resolve that, i just can't seem to get a filter by userid to work. Is this something you would consider adding, or advising how I could do it locally?

regards

Steve

**Comment by citykidz** [comment]
This looks great.  How can I see all of my plans; only some of them are listed?

**Comment by TerhoAntila** [comment]
Hi Steve and sory for LATE reply :| Planner connector (https://docs.microsoft.com/en-us/connectors/planner/) does not provide a method to search tasks over plan in any way. I think only way to achieve this would be to fetch all the plans for the current user -> fetch all the tasks for each of the plan -> do the search against all accumulated tasks. This is not a good approach, as a single user could have dozens of plans...

**Comment by TerhoAntila** [comment]
Closing this issue as nothing can be done about it really, as the Planner connector does not support it.
