### ISSUE TITLE
Gantt Chart start/end on the wrong date for a task period include this/last year or this/next year

### ISSUE THREAD

**Issue by JaneWCWu** [TerhoAntila/planner-gantt-chart#13]
Hi Terho,
Thanks a lot for your perfect app to make Planner a better planning tool! 
Please refer the task in planner gantt chart that i found the start/end date is not correct. It seems it happens when the task time span over 2 years (Show planner gantt chart for 1 year). But not all this kind of task date range wrong.
Please kinldy help to check it if it's possible. Thanks.

![PlannerGanttChart_01](https://user-images.githubusercontent.com/121612365/209943760-4ea3fd98-4ec3-4f31-94a2-c806a96a8409.png)
![PlannerGanttChart_02](https://user-images.githubusercontent.com/121612365/209943765-ca390656-3efc-40c9-8c34-2b9489087dd5.png)
![PlannerGanttChart_03](https://user-images.githubusercontent.com/121612365/209943766-53435d4e-b1b1-417b-8802-5dc43a7093b5.png)
![PlannerGanttChart_04](https://user-images.githubusercontent.com/121612365/209943767-230e542d-4a29-4fb6-84fb-846bd04dee21.png)

**Comment by TerhoAntila** [comment]
This now fixed in the latest version.
