### ISSUE TITLE
Errors regarding Assignees Photo MetaData

### ISSUE THREAD

**Issue by binaryjam** [TerhoAntila/planner-gantt-chart#2]
Hi I had this error,  now this is probably something wrong in my tenant, but it did make me look at the Assignees code to try and fix it,

Here are my changes,  it didn't solve this error message, but it did enhance it somewhat, perhaps consider the tooltip element as an enhancement request, the rest well, it may or not may be of use, 

Office365Users.UserPhotoMetadata failed: { "error": { "code": "UnknownError", "message": "{\r\n \"errorCode\": \"EnterpriseEntityNotFound\",\r\n \"message\": \"Accessing identity not a consumer, so async provisioning of mailbox (a.k.a. 'shard') for target identity was aborted\",\r\n \"target\": null,\r\n \"details\": null,\r\n \"innerError\": null,\r\n \"instanceAnnotations\": []\r\n}", "innerError": { "date": "2021-10-12T15:25:27", "request-id": "278a23e7-5...

So I changed mine to this to try and fix it, it didn't.

galAssignees.Items = 

AddColumns(
    ThisItem._assignments,
    "displayName",
    IfError (Office365Users.UserProfileV2(userId).displayName, "Unknown"),
    "photo",
    IfError(Office365Users.UserPhoto(userId),""),
    "hasPhoto",
    IfError(Office365Users.UserPhotoMetadata(userId).HasPhoto, false)
)

I changed the Image.Tooltip = ThisItem.displayName,   I also chanegs the Image.Image code to just HasImage since the parent code doesnt pass the whole object now.

So this bit was nice. Perhaps Add this bit whilst I chase MS support on why I'm getting this error message.

**Comment by TerhoAntila** [comment]
Thanks @binaryjam for the tip - it's a good practice to use the IfError function and I added your suggested gatAssignees.Items changes to the next version of the app.

**Comment by matteotrachsel** [comment]
Hi, 
first you have made a great app!
I still get kind of the same error.
![2022-12-07 12_53_16-Interview_ServicePartner_en docx - Word](https://user-images.githubusercontent.com/9714679/207565674-0edde938-d87e-4cdf-b70d-6ef5ef5f098a.png)
``Fehler bei "Office365Users.UserPhotoMetadata": 
{ "error": { "code": "UnknownError", "message": "{\r\n \"errorCode\": \"ErrorBadRequestInvalidTargetProfile\",\r\n \"message\": \"Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileBadRequestException' was thrown.\",\r\n \"target\": null,\r\n \"details\": null,\r\n \"innerError\": null,\r\n \"instanceAnnotations\": []\r\n}", "innerError": { "date": "2022-12-12T10:00:50", "request-id": "76c06070-b180-4f05-a467-9abf863b3585", "client-request-id": "76c06070-b180-4f05-a467-9abf863b3585" } } }``

Is this the same error or something new?
