### ISSUE TITLE
Support for versioning features by Git

### ISSUE THREAD

**Issue by suzuki-shm** [TerhoAntila/planner-gantt-chart#3]
Hi! Thank you very much for developing a very useful application.

Do you have any plans to make this repository configuration compatible with [Git versioning](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/git-version-control) ?

We are running the application with language localization and other support, but it makes difficult to apply your updates for that reason. We may have to redo the localization from scratch.
If you could make the repository compatible with Git versioning, updating would be possible by merging.
Please consider this for better use of this application.

**Comment by TerhoAntila** [comment]
Thanks TaskeHAMANO for the suggestion. The source files are now available in **gantt-chart-src** folder. I also wrote a short blog article about this: https://terhoantila.com/2022/03/19/planner-gantt-chart-source-files-now-in-github/
