### ISSUE TITLE
Task not matching dates

### ISSUE THREAD

**Issue by jamesbb93** [TerhoAntila/planner-gantt-chart#7]
@TerhoAntila 

Firstly, what a fantastic tool you've created!

I've stumbled across an issue which I believe is a bug.

Dates that fall within the selected date period on the gantt chart work without issue, but when I created a task that started 23 Mar 2018 and finished 5 Mar 2022, the dates don't match the input and the task isn't aligned as expected. See attached images for reproduction.

Would really like some help with this :)

![image](https://user-images.githubusercontent.com/103031160/161719900-be589f5a-a404-4168-a788-b2f7f44206fa.png)

**Comment by afabozzi** [comment]
This is an awesome tool!! I unfortunately have the same issue for projects that stretch several years :-(

Any suggestions?

**Comment by TerhoAntila** [comment]
The issue with long lasting tasks and dates is now fixed in the latest version of the app :)
