### ISSUE TITLE
Feature Request: Display assignee on left axis

### ISSUE THREAD

**Issue by markcs** [TerhoAntila/planner-gantt-chart#8]
This is excellent!

I was wondering if it would be possible to add an option where the Assignee's name could be shown in the left column instead of the Bucket.  This would give an overview of a person's load/downtime.

Let me know if I didn't explain that properly?

Thanks

**Comment by TerhoAntila** [comment]
This is a bit complicated request, since Planner allows having multiple assignees on a single task. With this feature request it would mean that there can be multiple names on one row in the left axis (in a similar way as it is now with labels/categories on the right axis)
